// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

void* winrt_make_AsioSDK_Class()
{
    return winrt::detach_abi(winrt::make<winrt::AsioSDK::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::AsioSDK
{
    Class::Class() :
        Class(make<AsioSDK::implementation::Class>())
    {
    }
}
