// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#include "pch.h"
#include "winrt/base.h"
void* winrt_make_AsioSDK_Class();

bool __stdcall AsioSDK_can_unload_now() noexcept
{
    if (winrt::get_module_lock())
    {
        return false;
    }

    winrt::clear_factory_cache();
    return true;
}

void* __stdcall AsioSDK_get_activation_factory([[maybe_unused]] std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"AsioSDK.Class"))
    {
        return winrt_make_AsioSDK_Class();
    }

    return nullptr;
}
