// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_AsioSDK_2_H
#define WINRT_AsioSDK_2_H
#include "winrt/impl/AsioSDK.1.h"
WINRT_EXPORT namespace winrt::AsioSDK
{
    struct __declspec(empty_bases) Class : winrt::AsioSDK::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::AsioSDK::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
